@extends('layouts.app')
@section('title', 'Batch Orders')
@section('content')
    <h2>Batch Orders</h2>

    <form action="{{ route('orders.batch') }}" method="post">
        @csrf
        <table border="1" class="table Bordered Table table-striped">
            <thead>
                <tr>
                    <th> ID </th>
                    <th>Batch No</th>
                    <th>Tag</th>
                    <th>Status</th>
                    <th>Generation date</th>
                    <th>Orders</th>
                    <th>Generated by</th>
                    <th>Labels and documents</th>

                </tr>
            </thead>
            <tbody>
                @foreach($orders['batchOrders'] as $order)
                <tr>
                    <td>{{ $order['id'] }}</td>
                    <td>{{ $order['batch_no'] }}</td>
                    <td>{{ $order['tag'] }}</td>
                    <td>{{ $order['status'] }}</td>
                    <td>{{ $order['generation_data'] }}</td>
                    <td>{{ $order['orders'] }}</td>
                    <td>{{ $order['generation_by'] }}</td>
                    <td>{{ $order['labelsanddocuments	'] }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </form>
@endsection
